version: "3.9"

services:
  foodapi:
    build:
      context: .
      dockerfile: "JustEatIt.FoodAPI/Dockerfile"
    ports:
      - 7000:80
  drinkapi:
    build:
      context: .
      dockerfile: "JustEatIt.DrinkAPI/Dockerfile"
    ports:
      - 7001:80
  orderapi:
    build:
      context: .
      dockerfile: "JustEatIt.OrderAPI/Dockerfile"
    ports:
      - 7002:80
  
